#!/bin/bash
script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [[ "$OSTYPE" == "msys" ]]; then
    mathjax="$(dirname "${script_dir}")/Library/lib/mathjax/MathJax.js"
else
    mathjax="$(dirname "${script_dir}")/lib/mathjax/MathJax.js"
fi

if [[ -f "$mathjax" ]]; then
    echo "$mathjax"
else
    echo -e "Error: $mathjax file was not found"
    exit 1
fi
