{% set name = "mathjax" %}
{% set version = "3.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mathjax/MathJax/archive/{{ version }}.tar.gz
  sha256: 4206b9645a97f431018d0b6c4021c98607d49ba4dc129f4f2ecce675e2fcba11

build:
  number: 0
  skip: true  # [not win]

requirements:
  build:
    - m2-bash  # [win]
      #- posix  # [win]

test:
  requires:
    - m2-bash  # [win]
      #- posix  # [win]
  commands:
    - mathjax-path  # [unix]
    - test -f "$(mathjax-path)latest.js"  # [unix]
    - cmd /c "%PREFIX%\Scripts\mathjax-path.bat"  # [win]
    - bash "%PREFIX%\Scripts\mathjax-path"  # [win]

about:
  home: https://github.com/mathjax/MathJax
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: |
    Beautiful math in all browsers. MathJax is an open-source JavaScript display engine for LaTeX, 
    MathML, and AsciiMath notation that works in all browsers. (use mathjax-path script)
  description: |
    MathJax is an open-source JavaScript display engine for LaTeX, MathML, and AsciiMath notation 
    that works in all modern browsers. It was designed with the goal of consolidating the recent 
    advances in web technologies into a single, definitive, math-on-the-web platform supporting the
    major browsers and operating systems. It requires no setup on the part of the user (no plugins
    to download or software to install), so the page author can write web documents that include 
    mathematics and be confident that users will be able to view it naturally and easily. Simply 
    include MathJax and some mathematics in a web page, and MathJax does the rest.
  doc_url: https://github.com/mathjax/MathJax
  dev_url: https://github.com/mathjax/MathJax

extra:
  recipe-maintainers:
    - kiwi0fruit
    - tdegeus
