{% set name = "mathjax" %}
{% set version = "3.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mathjax/MathJax/archive/{{ version }}.tar.gz
  sha256: 786f9a70f0a4d65d600118d1322be55c6c9b101a2bb9445f146a2cef9c4f074e

build:
  number: 0

test:
  commands:
    - mathjax-path  # [unix]
    - test -f "$(mathjax-path)latest.js"  # [unix]
    - cmd /c "%PREFIX%\Scripts\mathjax-path.bat"  # [win]
    - bash "%PREFIX%\Scripts\mathjax-path"  # [win]

about:
  home: https://github.com/mathjax/MathJax
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Beautiful math in all browsers. MathJax is an open-source JavaScript display engine for LaTeX, MathML, and AsciiMath notation that works in all browsers. (use mathjax-path script)
  doc_url: https://github.com/mathjax/MathJax
  dev_url: https://github.com/mathjax/MathJax

extra:
  recipe-maintainers:
    - kiwi0fruit
    - tdegeus
